### DISCUSSION TITLE
Not working with latest Airflow Helm Chart

### DISCUSSION THREAD

**Discussion by VfFlash** [andreax79/airflow-code-editor#84] [Announcements]
Hi,

First of all: thank you for this great idea and work!!! Unfortunately, I couldn't manage to use it when deployed to an AKS via the latest airflow helm chart, using airflow version 2.8.3: any dag-py file (that I create with this plugin) and store under `/opt/airflow/dags` doesn't either show up in the dag section - or it isn't added to DagBag when using `airflow dags reserialize`. The logs don't reveal much more information.

Is it possible that the plugin can't be used in the aks context? 

Thanks for your help!!

**Comment by VfFlash** [comment]
Sry that I labeled my question as a bug - I didn't know how else to get in contact with you.

**Comment by josedev-union** [comment]
I experienced the same issue and figured out what the problem is.
This code editor stores DAG files in airflow-webserver. Airflow helm charts for  `airflowVersion > 2.0`, it deploys airflow-scheduler as a separate pod along side the airflow-webserver, and DAGs files should be stored inside the airflow-scheduler pod. https://github.com/apache/airflow/blob/cae96630e1ddc1d3aae867c41d137e1d1fd7d465/chart/templates/webserver/webserver-deployment.yaml#L271-L283 
As long as webserver and schedulerr pods are not using a shared volume for DAGs files, this code editor will not work.

As a workaround, we can create a RWX volume and mount it on both webserver and scheduler pods, at dags file path.

**Comment by josedev-union** [comment]
Here is my custom values with verion 1.13.1 chart.
```yaml
dags:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: azurefile-csi
    accessMode: ReadWriteMany
webserver:
  extraVolumes:
    - name: dags
      persistentVolumeClaim:
        claimName: airflow-staging-dags
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
```
You'll need to change the claimName based on your helm release name. My helm release name is airflow-staging.
